# Generated by Django 3.2.15 on 2022-08-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата события')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='количество показов')),
                ('clicks', models.IntegerField(blank=True, null=True, verbose_name='количество кликов')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='стоимость кликов')),
            ],
        ),
    ]
