# Generated by Django 3.2.15 on 2022-08-12 06:30

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_statistics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='clicks',
            field=models.IntegerField(blank=True, null=True, validators=[api.validators.validate_value], verbose_name='количество кликов'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='cost',
            field=models.FloatField(blank=True, null=True, validators=[api.validators.validate_value], verbose_name='стоимость кликов'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='views',
            field=models.IntegerField(blank=True, null=True, validators=[api.validators.validate_value], verbose_name='количество показов'),
        ),
    ]
